### ISSUE TITLE
/v2/characters exceptions

### ISSUE THREAD

**Issue by madou** [arenanet/api-cdi#354]
Hey,

I seem to be getting this exception when accessing the characters endpoint, figured I'd post it here to see what you think.

Not sure of the token used to be honest as this is from my fetch container, but let me know if you need me to do more digging.

Cheers,
madou

```
<Error code="48" module="3" line="467" text="callback (): TypeError: Cannot read property 'sort' of undefined&#xA;TypeError: Cannot read property 'sort' of undefined&#xA;
at async.map (c:\arenanet\llivewebapi.337\web\js2api\code\v2\controllers\account\characters.js:75:44)&#xA;    
at c:\arenanet\llivewebapi.337\web\js2api\node_modules\async\lib\async.js:52:16&#xA;    
at c:\arenanet\llivewebapi.337\web\js2api\node_modules\async\lib\async.js:363:13&#xA;    
at c:\arenanet\llivewebapi.337\web\js2api\node_modules\async\lib\async.js:52:16&#xA;    
at done (c:\arenanet\llivewebapi.337\web\js2api\node_modules\async\lib\async.js:248:21)&#xA;    
at c:\arenanet\llivewebapi.337\web\js2api\node_modules\async\lib\async.js:44:16&#xA;    
at c:\arenanet\llivewebapi.337\web\js2api\node_modules\async\lib\async.js:360:17&#xA;    
at fetchItemDetails (c:\arenanet\llivewebapi.337\web\js2api\code\v2\controllers\account\characters.js:54:24)&#xA;    
at c:\arenanet\llivewebapi.337\web\js2api\code\v2\lib\memoize.js:62:24&#xA;    
at request.gamegate (c:\arenanet\llivewebapi.337\web\js2api\code\v2\controllers\items\lib.js:58:24)"/>
```

**Comment by tivac** [comment]
Yes, we'll need a token to investigate further.

**Comment by madou** [comment]
I'll close this for now, I can't find the problematic token.

If can give you more specifics in the future I'll re-open this.

Cheers,
madou

**Comment by tivac** [comment]
Ok definitely circle back around if you can provide help reproing!
